### ISSUE TITLE
feat: migrate to `vercel`

### ISSUE THREAD

**Issue by Ahwxorg** [teamblueprint/web#4]
Might be nice to migrate to [Vercel](https://vercel.com). GitHub is nice but not as-nice as Vercel in my opinion. No real reasoning :P

**Comment by prplwtf** [comment]
GitHub Pages is fine in my (automatically correct) opinion.

**Comment by Ahwxorg** [comment]
[click](https://www.youtube.com/watch?v=FgPWXw346Y8)

**Comment by prplwtf** [comment]
funni

**Comment by Slimi1** [comment]
How ban?

**Comment by prplwtf** [comment]
no ban

**Comment by Slimi1** [comment]
Yes ban

**Comment by Ahwxorg** [comment]
This is all fun and games, I know prpl, no worries.

**Comment by Slimi1** [comment]
I know purpur too
